name: Feature Request
description: Suggest a new feature or improvement.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like the app to do?
      description: Describe the feature or improvement.
      placeholder: "It would be useful if the app could..."
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: How would you use this?
      description: Describe a practical scenario where this feature would help.
      placeholder: "During boiling season, I need to..."
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Android
        - iOS
        - Both
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you tried any workarounds?
    validations:
      required: false
